INSERT INTO awards (id, name, description, icon) VALUES (1, 'Newborn', 'User just registered and started using the site.', 'img/awards/newborn.png');
INSERT INTO awards (id, name, description, icon) VALUES (2, 'Let''s Make Money!', 'User created their first event.', 'img/awards/money.png');
INSERT INTO awards (id, name, description, icon) VALUES (3, 'Organizer', 'Created 10+ events.', 'img/awards/sandwich.png');
INSERT INTO awards (id, name, description, icon) VALUES (4, 'High Five!', 'User was rated 5 stars for an event.', 'iimg/awards/highfive.png');
INSERT INTO awards (id, name, description, icon) VALUES (5, 'Beta Tester', 'User tested the website while in beta.', 'img/awards/beta.png');
INSERT INTO awards (id, name, description, icon) VALUES (6, 'Ice Scream, You Scream', 'Rated an ice cream event.', 'img/awards/icecream.png');
INSERT INTO awards (id, name, description, icon) VALUES (7, 'Pizza, Pizza', 'Rated a pizza event.', 'img/awards/pizza.png');
INSERT INTO awards (id, name, description, icon) VALUES (8, 'Mobile Me', 'Subscribed to an event with SMS.', 'img/awards/phone.png');
INSERT INTO awards (id, name, description, icon) VALUES (9, 'Fan-Tack-Stic!', 'Tacked up an event to attend.', 'img/awards/tack.png');
INSERT INTO awards (id, name, description, icon) VALUES (10, 'Popular', 'Have 20+ people ‘tack’ your event.', 'img/awards/people.png');